name: CI Pipeline 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      
      - name: Restore and build the solution
        working-directory: ./api/Basic3TierAPI
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      #- name: Run tests (Basic3TierAPI.Tests is empty)
      #  working-directory: ./api/Tests
      #  run: |
      #    dotnet test --no-build --configuration Release

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-ui:latest ./ui
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-api:latest ./api

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-ui:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-api:latest
      
      - name: Debug Repository Name
        run: echo "Repository ${{ github.repository }}"
      
      - name: Check Workflows List
        if: ${{ success() }}
        run: |
         curl -v -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/najjaved/cicd-3-tier-application/actions/workflows"


      - name: Trigger CD Pipeline
        if: ${{ success() }}
        # curl makes a POST request to the GitHub Actions API
        run: |
          curl --http1.1 -v -X POST \
           -H "Accept: application/vnd.github.v3+json" \
           -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
           -H "Content-Type: application/json" \
           --data '{"ref":"main"}' \
           https://api.github.com/repos/najjaved/${{ github.repository }}/actions/workflows/cd-pipeline.yml/dispatches


